import { PortfolioData } from "./types";

export const initialPortfolioData: PortfolioData = {
  profile: {
    name: "유수경",
    engName: "Yoo Su-kyung",
    title: "Content Designer & Performance Creative",
    headline: "유수(流水)같이 흐르는 매끄러운 기획으로 시선을 사로잡는 디자이너 유수경 입니다.",
    subHeadline: "광고 소재 기획부터 SNS 콘텐츠 운영, 바이럴 영상 제작까지, 사용자의 시각적 유도를 다각도로 설계하는 종합 디자이너입니다.",
    idPhoto: ""
  },
  stats: [
    { id: "s1", value: "2년+", label: "퍼포먼스 콘텐츠 설계 경험" },
    { id: "s2", value: "100+", label: "광고 소재 기획 & 디자인" },
    { id: "s3", value: "50+", label: "바이럴 숏폼 영상 제작 총괄" },
    { id: "s4", value: "15만", label: "최대 오가닉 조회수" }
  ],
  strengths: [
    {
      id: "str-1", title: "Performance Creative", subtitle: "메타 최적화 광고 소재 설계",
      points: ["소비자 시인성 분석에 기반한 레이아웃 설계", "첫 시선을 저격하는 후킹 카피 배치", "Visual Hierarchy 중심의 썸네일 구조화"]
    },
    {
      id: "str-2", title: "Viral Short-form", subtitle: "숏폼 비디오 크리에이티브",
      points: ["인스타그램 릴스 및 유튜브 쇼츠 맞춤형 기획", "이탈률을 최소화하는 초반 3초 핵심 후킹 설계", "현장감을 전달하는 다이나믹 영상 편집"]
    },
    {
      id: "str-3", title: "SNS Management", subtitle: "브랜드 채널 마케팅 비주얼 운영",
      points: ["브랜드 아이덴티티에 충실한 피드 그리드 구축", "지속적인 피드백 기반 마케팅 콘텐츠 기획", "오가닉 타겟 도달 성과 극대화를 위한 브랜딩"]
    },
    {
      id: "str-4", title: "Rapid Design", subtitle: "Figma 고속 가공",
      points: ["신속한 멀티채널 시안 제작 속도", "마스터 컴포넌트를 활용한 바리에이션 제작", "소통 비용 최소화 협업 파이프라인"]
    }
  ],
  projects: [
    {
      id: "p1", title: "청년철거 SNS 브랜드 비주얼 빌드",
      category: "SNS Brand Account Operation",
      tagline: "현장감을 극대화한 오가닉 숏폼 콘텐츠로, 거친 시공 기업의 이미지를 친근하고 직관적으로 개편했습니다.",
      problem: "철거 및 시공 업종의 특성상 무겁고 거친 편견이 강하여, 오가닉 채널 소통과 일반 대중의 접근성이 결여되어 있었습니다.",
      strategy: "작업 전후(Before/After) 숏폼, 현장 비하인드 에피소드, 철거 과정 정밀 대조 콘텐츠 등 친밀도 높은 비디오 레이아웃을 도입하여 재미와 신뢰도를 강화했습니다.",
      results: ["인스타그램 누적 오가닉 조회수 최대 15만회 돌파 달성", "비주얼 리바운딩 후 오가닉 채널 팔로워 수 240% 성장 기록", "투명한 과정 공개 콘텐츠 중심의 고객 채널 신뢰 저변 확보"],
      imageType: "social"
    },
    {
      id: "p2", title: "에고랩스 퍼포먼스 광고 소재 비주얼 고도화",
      category: "Performance Creative Design Study",
      tagline: "타겟 소구점 분석과 모바일 화면 시인성 개편을 주도하여 크리에이티브 시각 가이드를 설계했습니다.",
      problem: "기존 제작 배너들의 소구 지점 정체와 모바일 디스플레이 특성에 맞지 않는 글씨 위계로 인해 유입 주목도가 갈수록 약화되고 있었습니다.",
      strategy: "업계 우수 경쟁사 광고 레퍼런스 50여 종 심층 분석을 토대로 즉시 인지 중심의 핵심 볼드 서체 가이드 수립, 엄격히 규격화된 디바이스 전용 컴포넌트 템플릿 제작.",
      results: ["시각 편의 위주 썸네일 시뮬레이션 테스트에서 반응 호감도 우위 확인", "사이즈 다변화 프로세스 단축으로 디자이너 작업 효율 2.5배 가속화", "가장 직관적인 가독성의 최적 프레임을 팀 공식 광고 디자인 가이드라인으로 전격 채택"],
      imageType: "ad"
    },
    {
      id: "p3", title: "스튜디오 피엘 감성 테라스 통합 브랜딩 디자인",
      category: "Custom Product Visual & Shorts",
      tagline: "오토레이아웃 기반 디자인 자산 구축 및 유튜브 쇼츠 기획으로 3초 이내 이탈률을 최소화했습니다.",
      problem: "제품의 프리미엄 감성이 모바일 디스플레이 화면에 충분히 도식화되지 못하여 고가 카테고리의 신뢰도를 어필하는 데 한계가 있었습니다.",
      strategy: "Figma 컴포넌트화 시스템을 적용해 이미지 배너의 로고 위계와 여백 비율을 전면 재조정하고, 감성 중심의 릴스 숏폼 무드와 다이나믹 로고 배치를 혼합해 모바일 유입 도달 속도를 높였습니다.",
      results: ["Figma 원격 가이드 배포 후 파트너사 채널 협업 소통 비용 약 300% 이상 절감", "초반 3초 후킹 자막 레이아웃 기법 도입으로 비디오 평균 시청 지속 시간 45% 증가", "모바일 디스플레이 가독성 개선으로 채널 반응 호감도 및 문의 도달율 대폭 성장"],
      imageType: "ad"
    }
  ],
  processSteps: [
    {
      id: "proc-1", phase: "01",
      title: "브랜드 전략 수립 및 핵심 카피라이팅",
      desc: "담당 브랜드(청년철거, 국대간판 등)의 소셜 미디어 포지셔닝과 타겟 페르소나를 심층 분석합니다. 이를 바탕으로 소비자 인지도를 극대화할 수 있는 후킹(Hooking) 카피를 발굴하고, 캠페인의 핵심 메시지를 전략적으로 기획합니다."
    },
    {
      id: "proc-2", phase: "02",
      title: "시각 리소스 기획 및 레이아웃 설계",
      desc: "Figma를 활용하여 사용자 경험과 가독성을 고려한 트렌디한 카드뉴스 레이아웃을 구축합니다. 브랜드 아이덴티티(BI)에 완벽하게 부합하는 맞춤형 그래픽 소스를 정교하게 디자인하여 콘텐츠의 시각적 완성도를 높입니다."
    },
    {
      id: "proc-3", phase: "03",
      title: "생성형 AI 기반 오디오 리소스 최적화",
      desc: "Suno, ElevenLabs 등 최신 생성형 AI 솔루션을 실무 워크플로우에 적극 도입하여 제작 효율을 극대화합니다. 기획 의도에 최적화된 BGM을 생성하고, 자연스러운 AI 보이스오버를 추출하여 콘텐츠의 청각적 디테일을 확보합니다."
    },
    {
      id: "proc-4", phase: "04",
      title: "에셋 통합 및 영상 편집 고도화",
      desc: "Premiere Pro를 활용해 자체 제작한 시각 디자인 에셋과 AI 오디오 리소스를 유기적으로 결합합니다. 플랫폼별 매체 특성에 맞춘 정밀한 컷편집과 시각적 몰입도를 높이는 모션 이펙트를 적용해 최종 영상 퀄리티를 고도화합니다."
    },
    {
      id: "proc-5", phase: "05",
      title: "실무 크로스체크 및 퀄리티 컨트롤",
      desc: "실무진과의 긴밀한 협업 프로세스를 통해 1차 시안의 톤앤매너, 시각적 디테일, 브랜드 정합성 등을 다각도로 검증합니다. 능동적인 상호 피드백 수용과 수정 작업을 거쳐 결과물의 전반적인 완성도를 최상으로 끌어올립니다."
    },
    {
      id: "proc-6", phase: "06",
      title: "최종 리포팅 및 매체별 퍼블리싱",
      desc: "프로젝트 책임자에게 마케팅 진행 상황과 최종 산출물을 체계적으로 리포팅합니다. 검토가 완료된 콘텐츠는 각 브랜드 공식 채널의 알고리즘 및 유저 반응 시간대에 최적화된 방식으로 발행하여 실질적인 캠페인 성과를 창출합니다."
    }
  ],
  skills: [
    { id: "sk1", category: "Design", name: "Figma", rating: 5 },
    { id: "sk2", category: "Design", name: "Photoshop", rating: 4 },
    { id: "sk3", category: "Design", name: "Illustrator", rating: 3 },
    { id: "sk4", category: "Video", name: "Premiere Pro", rating: 5 },
    { id: "sk5", category: "Video", name: "After Effects", rating: 4 },
    { id: "sk7", category: "Marketing", name: "Instagram 운영", rating: 5 },
    { id: "sk8", category: "Marketing", name: "콘텐츠 기획", rating: 5 }
  ],
  careers: [
    {
      id: "c1", period: "2024.03 — 2024.08", company: "행복한 소리",
      role: "광고 디자이너 & 콘텐츠 디자이너",
      details: ["모바일 최적화 SNS 그래픽 가이드 및 시인 중심 소개 페이지 디자인 가공", "소비자 인식을 고려한 바이럴 마케팅 그래픽 시안 및 커뮤니티 배너 디자인", "다변화하는 광고 규격별 배너 변주 가공"]
    },
    {
      id: "c2", period: "2024.08 — 현재", company: "에고랩스 & 스튜디오 피엘",
      role: "광고 디자이너 & 콘텐츠 디자이너",
      details: ["정밀 소구 분석에 근거한 모바일 전용 주력 광고 크리에이티브 가이드라인 수립", "유튜브 쇼츠, 인스타그램 릴스 맞춤형 웰메이드 콘텐츠 편집 및 브랜드 채널 비주얼 리딩", "채널 그리드 디자인 통일 및 비포/애프터 비디오 구성을 통한 도달 가독성 대폭 향상"]
    }
  ],
  contact: { email: "dongmi244@naver.com", phone: "010-3760-4883" },
  portfolioWorks: [
    {
      id: "w-ego-스터디_1",
      title: "[에고랩스 스터디] 수능? 단 7일이면 됩니다 (남학생)",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892925/portfolio/dxrd24ryodazc2okl45e.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_2",
      title: "[에고랩스 스터디] 수능? 단 7일이면 됩니다 (여학생)",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892926/portfolio/ulq9gzamzh0qajrdqzsd.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_3",
      title: "[에고랩스 스터디] 단 한 포에 전교 1등 되는 방법",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892927/portfolio/gyc6jltc47rrmhz0wble.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_4",
      title: "[에고랩스 스터디] 약국 완판 수험생 올인원 — 특판가 링크 유출",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892928/portfolio/sdnroyl74p1eagpycevu.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_5",
      title: "[에고랩스 스터디] 우리 아이가 수능을 잘 볼 수 있을까요?",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892930/portfolio/v0esig5wk9ubeg7guoqf.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_6",
      title: "[에고랩스 스터디] 갱생불가 꼴등 → 전교 1등 비결",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892931/portfolio/pc4y2dnd9jluzshb7iha.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_7",
      title: "[에고랩스 스터디] ADHD 꼴등 → 상위 1% 전교 1등",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892934/portfolio/ljdw7i1rov2b64x7zmpp.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_8",
      title: "[에고랩스 스터디] S대 합격하고 저 진짜 눈물 흘렸습니다",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892935/portfolio/ji3qudrfqofjosxjw2vm.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_9",
      title: "[에고랩스 스터디] ADHD 극복하고 저 진짜 눈물 흘렸습니다",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892938/portfolio/vrhups8f9mt3qoggzas3.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_10",
      title: "[에고랩스 스터디] 대치동 수능 치트키템 — 죄송합니다",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892940/portfolio/xft0aciqtcsg7imcb1kk.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_11",
      title: "[에고랩스 스터디] 전교 1등 비밀 — 재고가 얼마 없어서 죄송합니다",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892942/portfolio/faha8dqswd6n7uazfgwz.jpg",
      workType: "image",
    },
    {
      id: "w-ego-스터디_12",
      title: "[에고랩스 스터디] 이 링크를 절대 공유하지 마세요",
      category: "에고랩스",
      description: "에고랩스 스터디 올인원팩 SNS 광고 크리에이티브. 수험생 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892944/portfolio/iv1dixpbvheobynjfzv6.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_1",
      title: "[에고랩스 밸런스업] 체력 박살 30대 → 활기 넘침 비결",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892945/portfolio/wov85byx3uhhvnr3ulr6.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_2",
      title: "[에고랩스 밸런스업] 예비 엄마 30대 → 자연임신성공 비결",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892946/portfolio/deilap0hkatxixh3llr8.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_3",
      title: "[에고랩스 밸런스업] 약국 완판 직장인 올인원 — 특판가 링크 유출",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892948/portfolio/xge2mr6mo668jd4agggc.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_4",
      title: "[에고랩스 밸런스업] 와! 진짜 너무 개운하다 (남성)",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892949/portfolio/rr0ijiyqocg2tutcigzn.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_5",
      title: "[에고랩스 밸런스업] 와! 진짜 너무 개운하다 (여성)",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892950/portfolio/pichc34jj1xzimg6ypqm.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_6",
      title: "[에고랩스 밸런스업] 30대 남성 번아웃 해결 방법",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892951/portfolio/pk9fvllmqkqreclrmgp6.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스업_7",
      title: "[에고랩스 밸런스업] 30대 여성 번아웃 해결 방법",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892953/portfolio/oudmygtsjbr5hpmaqze7.jpg",
      workType: "image",
    },
    {
      id: "w-ego-밸런스되",
      title: "[에고랩스 밸런스업] 밸런스업이 됩니다 (바이럴 밈 콘텐츠)",
      category: "에고랩스",
      description: "에고랩스 밸런스업 올인원팩 SNS 광고 크리에이티브. 30대 직장인/예비부모 타겟 퍼포먼스 광고 소재.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892953/portfolio/m6kxbrrvqsb9sumejgxu.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-스터디1",
      title: "[에고랩스 스터디] 스터디 올인원팩 — BLACK FRIDAY 최대 40% OFF (제품샷)",
      category: "에고랩스",
      description: "스터디 올인원팩 — BLACK FRIDAY 최대 40% OFF (제품샷) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892954/portfolio/mspne1bwcimlarw3vy3v.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-스터디2",
      title: "[에고랩스 스터디] 스터디 올인원팩 — BLACK FRIDAY 11.22-11.29",
      category: "에고랩스",
      description: "스터디 올인원팩 — BLACK FRIDAY 11.22-11.29 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892956/portfolio/lhd9rvwmnvwbnv085ms3.jpg",
      workType: "image",
    },
    {
      id: "w-new-241101-스터디됩",
      title: "[에고랩스 스터디] 스터디가 됩니다 (바이럴 밈 콘텐츠)",
      category: "에고랩스",
      description: "스터디가 됩니다 (바이럴 밈 콘텐츠) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892957/portfolio/yrfnjgehwnmpr9urqnsb.jpg",
      workType: "image",
    },
    {
      id: "w-new-241104-밸런스업1",
      title: "[에고랩스 밸런스업] 밸런스업 — 이미 구매하신 분들 정말 죄송합니다 (제품샷)",
      category: "에고랩스",
      description: "밸런스업 — 이미 구매하신 분들 정말 죄송합니다 (제품샷) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892958/portfolio/zjj0gnpnsdn0kw8t9iiv.jpg",
      workType: "image",
    },
    {
      id: "w-new-241104-밸런스업2",
      title: "[에고랩스 밸런스업] 밸런스업 — 이거 한 포면 끝! 미리 구매하신 분들 죄송합니다",
      category: "에고랩스",
      description: "밸런스업 — 이거 한 포면 끝! 미리 구매하신 분들 죄송합니다 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892959/portfolio/sllk7jzuvgl7y5s3aw1g.jpg",
      workType: "image",
    },
    {
      id: "w-new-241104-스터디1",
      title: "[에고랩스 스터디] 스터디 — 이미 구매하신 분들 정말 죄송합니다 (제품샷)",
      category: "에고랩스",
      description: "스터디 — 이미 구매하신 분들 정말 죄송합니다 (제품샷) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892960/portfolio/w8akhcbbqdi5s54n9trp.jpg",
      workType: "image",
    },
    {
      id: "w-new-241104-스터디2",
      title: "[에고랩스 스터디] 스터디 — 이거 한 포면 끝! 비밀링크 수험생 올인원 40% 할인",
      category: "에고랩스",
      description: "스터디 — 이거 한 포면 끝! 비밀링크 수험생 올인원 40% 할인 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892961/portfolio/anm9qglvwiupunu6v0u2.jpg",
      workType: "image",
    },
    {
      id: "w-new-241105-밸런스업-그림",
      title: "[에고랩스 밸런스업] 밸런스업 — 눈을 보세요 40% 할인 비밀링크 (일러스트)",
      category: "에고랩스",
      description: "밸런스업 — 눈을 보세요 40% 할인 비밀링크 (일러스트) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892962/portfolio/wlpvwf6rff8w0mgk7yxa.jpg",
      workType: "image",
    },
    {
      id: "w-new-241105-스터디-그림",
      title: "[에고랩스 스터디] 스터디 — 눈을 보세요 40% 할인 비밀링크 (일러스트)",
      category: "에고랩스",
      description: "스터디 — 눈을 보세요 40% 할인 비밀링크 (일러스트) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892963/portfolio/ykgxhq1yu8j7f3y8psqx.jpg",
      workType: "image",
    },
    {
      id: "w-new-241108-밸런스-약국",
      title: "[에고랩스 밸런스업] 밸런스업 — 약국 품절대란 현직 약사 강력 추천",
      category: "에고랩스",
      description: "밸런스업 — 약국 품절대란 현직 약사 강력 추천 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892964/portfolio/qnrdkosudwlez4agq68d.jpg",
      workType: "image",
    },
    {
      id: "w-new-241108-스터디-약국",
      title: "[에고랩스 스터디] 스터디 — 약국 품절대란 현직 약사 강력 추천",
      category: "에고랩스",
      description: "스터디 — 약국 품절대란 현직 약사 강력 추천 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892966/portfolio/w8fsmikpudms0x1z2jvw.jpg",
      workType: "image",
    },
    {
      id: "w-new-241108-품절대란-밸런스",
      title: "[에고랩스 밸런스업] 밸런스업 약국 품절 — 매일 오전 10시 입고",
      category: "에고랩스",
      description: "밸런스업 약국 품절 — 매일 오전 10시 입고 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892967/portfolio/aij95gurgxkyz6lz2iov.jpg",
      workType: "image",
    },
    {
      id: "w-new-241108-품절대란-스터디",
      title: "[에고랩스 스터디] 스터디 약국 품절 — 매일 오전 10시 입고",
      category: "에고랩스",
      description: "스터디 약국 품절 — 매일 오전 10시 입고 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892968/portfolio/wd4qa320jnvotkwai4bu.jpg",
      workType: "image",
    },
    {
      id: "w-new-241118-메모리업1",
      title: "[에고랩스 메모리업] 메모리업 — 엄마 오늘은 걱정 말고 푹 자 / 48,000원 특가",
      category: "에고랩스",
      description: "메모리업 — 엄마 오늘은 걱정 말고 푹 자 / 48,000원 특가 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892969/portfolio/zlgxjthbbyq9hc73kyeu.jpg",
      workType: "image",
    },
    {
      id: "w-new-241118-메모리업2",
      title: "[에고랩스 메모리업] 메모리업 — 아빠 오늘은 걱정 말고 푹 자 / 48,000원 특가",
      category: "에고랩스",
      description: "메모리업 — 아빠 오늘은 걱정 말고 푹 자 / 48,000원 특가 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892970/portfolio/oxdo11m706iwqudbvzjo.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-밸런스업1",
      title: "[에고랩스 밸런스업] 밸런스업 — BLACK FRIDAY 최대 40% OFF (제품샷)",
      category: "에고랩스",
      description: "밸런스업 — BLACK FRIDAY 최대 40% OFF (제품샷) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892971/portfolio/tnf5gcqafn0oqnxc6ib1.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-밸런스업2",
      title: "[에고랩스 밸런스업] 밸런스업 — BLACK FRIDAY 11.22-11.29",
      category: "에고랩스",
      description: "밸런스업 — BLACK FRIDAY 11.22-11.29 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892972/portfolio/v9icmwzqkgu2vqo6e1ak.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-밸런스업3",
      title: "[에고랩스 밸런스업] 밸런스업 — 40% 할인 특가 비밀링크 검색해도 안나옵니다",
      category: "에고랩스",
      description: "밸런스업 — 40% 할인 특가 비밀링크 검색해도 안나옵니다 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892973/portfolio/p2k5nzcxldo30ogcoia3.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-밸런스업5",
      title: "[에고랩스 밸런스업] 에고랩스 블랙프라이데이 — 40% 3D (밸런스업)",
      category: "에고랩스",
      description: "에고랩스 블랙프라이데이 — 40% 3D (밸런스업) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892974/portfolio/bbujut8jtarjvbfh8qfz.jpg",
      workType: "image",
    },
    {
      id: "w-new-241119-밸런스업6",
      title: "[에고랩스 밸런스업] 밸런스업 40% 올인원팩 블랙프라이데이 (3D 타이포)",
      category: "에고랩스",
      description: "밸런스업 40% 올인원팩 블랙프라이데이 (3D 타이포) — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892975/portfolio/lmenoeahqt6a4vcwdguy.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-밸런스업3",
      title: "[에고랩스 밸런스업] 밸런스업 — #활력부스터 하루 한 포에 30가지 영양소",
      category: "에고랩스",
      description: "밸런스업 — #활력부스터 하루 한 포에 30가지 영양소 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892976/portfolio/z3qp5uv3q6h7qmwe9yhz.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-밸런스업4",
      title: "[에고랩스 밸런스업] 밸런스업 — 건강:죽을게 돈:없을게 나:울게 에고랩스:세일할게",
      category: "에고랩스",
      description: "밸런스업 — 건강:죽을게 돈:없을게 나:울게 에고랩스:세일할게 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892977/portfolio/wrgt1igfk0o51k51dyrc.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-스터디1",
      title: "[에고랩스 스터디] 스터디 — 한 포에 천 원대 득템 찬스",
      category: "에고랩스",
      description: "스터디 — 한 포에 천 원대 득템 찬스 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892978/portfolio/ajnzzciqfvuus1wo0ckd.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-스터디2",
      title: "[에고랩스 스터디] 스터디 — 성적 향상 해달라고? 너 누군데?",
      category: "에고랩스",
      description: "스터디 — 성적 향상 해달라고? 너 누군데? — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892979/portfolio/e8ytrp0lbhmxayy4ra8s.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-스터디3",
      title: "[에고랩스 스터디] 스터디 — #학습부스터 하루 한 포에 27가지 영양소",
      category: "에고랩스",
      description: "스터디 — #학습부스터 하루 한 포에 27가지 영양소 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892980/portfolio/ph4simzqhqekovdg0pik.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241119-스터디3",
      title: "[에고랩스 스터디] 스터디 — BLACK FRIDAY 수험생 비밀링크 검색해도 안나옵니다",
      category: "에고랩스",
      description: "스터디 — BLACK FRIDAY 수험생 비밀링크 검색해도 안나옵니다 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892981/portfolio/zf1zzo7rmzd7pnixd5w6.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241119-스터디5",
      title: "[에고랩스 스터디] 스터디 — 에고랩스 블랙프라이데이 40% 3D",
      category: "에고랩스",
      description: "스터디 — 에고랩스 블랙프라이데이 40% 3D — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892982/portfolio/ypfwh4pes8qlf7mh4oyt.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241119-스터디6",
      title: "[에고랩스 스터디] 스터디 — 40% 올인원팩 블랙프라이데이 3D 타이포",
      category: "에고랩스",
      description: "스터디 — 40% 올인원팩 블랙프라이데이 3D 타이포 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892984/portfolio/klb8nowk6yk0pnubo94f.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241120-밸런스업",
      title: "[에고랩스 밸런스업] 밸런스업 — 한꺼번에 다 챙겨먹을 수 있으니까! 밸런스업 한 포",
      category: "에고랩스",
      description: "밸런스업 — 한꺼번에 다 챙겨먹을 수 있으니까! 밸런스업 한 포 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892985/portfolio/sjk5a5fe8hg5bd9x3ct5.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241120-스터디",
      title: "[에고랩스 스터디] 스터디 — 한꺼번에 다 챙겨먹을 수 있으니까! 스터디 한 포",
      category: "에고랩스",
      description: "스터디 — 한꺼번에 다 챙겨먹을 수 있으니까! 스터디 한 포 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892986/portfolio/pnh8gwc9qucgctedjwlu.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-밸런스업1",
      title: "[에고랩스 밸런스업] 밸런스업 — 고객님 죄송합니다 7일 남은 40% 할인",
      category: "에고랩스",
      description: "밸런스업 — 고객님 죄송합니다 7일 남은 40% 할인 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892987/portfolio/x0qcgbbfsm8pnhg2ea6f.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-밸런스업2",
      title: "[에고랩스 밸런스업] 밸런스업 — 하루 한 포로 피로삭제 47,400원 비밀링크",
      category: "에고랩스",
      description: "밸런스업 — 하루 한 포로 피로삭제 47,400원 비밀링크 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892988/portfolio/sqhzl3qo6rnrha5ugfin.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-밸런스업3",
      title: "[에고랩스 밸런스업] 밸런스업 — 가격 찢었다 남성 필수 올인원 부스터",
      category: "에고랩스",
      description: "밸런스업 — 가격 찢었다 남성 필수 올인원 부스터 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892989/portfolio/w8mm6njdzc3rmklbmvbd.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-밸런스업4",
      title: "[에고랩스 밸런스업] 밸런스업 — 남자 벌크업 필수 영양 성분",
      category: "에고랩스",
      description: "밸런스업 — 남자 벌크업 필수 영양 성분 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892990/portfolio/ow7satumkbm4njo32edv.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-스터디1",
      title: "[에고랩스 스터디] 스터디 — 고객님 죄송합니다 7일 남은 40% 할인",
      category: "에고랩스",
      description: "스터디 — 고객님 죄송합니다 7일 남은 40% 할인 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892991/portfolio/emavyjdfu6sywyorkutm.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-스터디2",
      title: "[에고랩스 스터디] 스터디 — 하루 한 포로 성적향상 48,000원 비밀링크",
      category: "에고랩스",
      description: "스터디 — 하루 한 포로 성적향상 48,000원 비밀링크 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892992/portfolio/dt058qx064vqrldnx2gw.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-스터디3",
      title: "[에고랩스 스터디] 스터디 — 가격 찢었다 학생 필수 올인원 부스터",
      category: "에고랩스",
      description: "스터디 — 가격 찢었다 학생 필수 올인원 부스터 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892993/portfolio/syrzkotdutapgoeqe7mv.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241125-스터디4",
      title: "[에고랩스 스터디] 스터디 — 수험생 공부 필수 영양 성분",
      category: "에고랩스",
      description: "스터디 — 수험생 공부 필수 영양 성분 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892994/portfolio/iluwmqchvmq5ms1bxpxh.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-밸런스업1",
      title: "[에고랩스 밸런스업] 밸런스업 — 한 포에 천 원대 득템 찬스",
      category: "에고랩스",
      description: "밸런스업 — 한 포에 천 원대 득템 찬스 — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892995/portfolio/q8rkyudg06k8ina06v02.jpg",
      workType: "image",
    },
    {
      id: "w-b3-241126-밸런스업2",
      title: "[에고랩스 밸런스업] 밸런스업 — 피로 삭제 해달라고? 너 누군데?",
      category: "에고랩스",
      description: "밸런스업 — 피로 삭제 해달라고? 너 누군데? — 퍼포먼스 광고 소재 크리에이티브.",
      imageUrl: "https://res.cloudinary.com/dyihk6tei/image/upload/v1780892996/portfolio/ib2bfygmfgjf5kwdzsyu.jpg",
      workType: "image",
    },
  ],
  whyMe: {
    title: "왜 저를 채용해야 할까요?",
    description: "저는 픽셀만 정돈하는 기계적 디자이너가 아닙니다. 콘텐츠가 소비되는 시점부터의 인지 흐름을 정교히 설계합니다.",
    points: [
      "퍼포먼스 마케팅에 대한 깊은 유기적 이해: 클릭하는 유저의 심리와 시선 집중 법칙을 정확히 간파해 디자인 기획 단계에 직접 반영합니다.",
      "기획, 비주얼, 영상 가공까지 수행하는 올라운더: 메시지 발굴부터 숏폼 영상 제작 및 채널 그리드 운영까지 전부 소화합니다.",
      "소통 및 생산 시간 단축에 강한 디자이너: Figma 최적화 오토 컴포넌트를 활용하여 광고 크기별 바리에이션을 신속히 가공하고 실무 마찰을 줄입니다."
    ]
  },
  tools: [
    { id: "t1", name: "Figma", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
    { id: "t2", name: "Photoshop", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
    { id: "t3", name: "Illustrator", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
    { id: "t4", name: "Premiere Pro", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/premierepro/premierepro-plain.svg" },
    { id: "t5", name: "After Effects", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aftereffects/aftereffects-plain.svg" }
  ],
  design: {
    primaryColor: "#0ea5e9",
    bgColor: "#ffffff",
    textColor: "#0f172a",
    cardBgColor: "#ffffff",
    navBgColor: "#ffffff",
    btnPrimaryColor: "#0ea5e9",
    btnPrimaryText: "#ffffff",
    btnPrimaryLabel: "포트폴리오",
    btnSecondaryColor: "#f0f9ff",
    btnSecondaryLabel: "연락망",
    heroBgType: "gradient",
    heroBgValue: "#e0f2fe",
    sectionOrder: ["about","projects","process","portfolio","skills","career","contact"],
    globalFontSize: "base",
  },
  sections: {
    about:    { badge: "01 | ABOUT // 자기소개",       title: "디자이너 유수경입니다.",                     subtitle: "광고 소재 기획부터 SNS 콘텐츠 운영, 바이럴 영상 제작 및 피그마 고속 설계 협업 최적화까지 시선과 호감을 유도하는 크리에이티브 가독성을 세팅합니다." },
    projects: { badge: "02 | CASE STUDY ANALYSIS",    title: "주도적 크리에이티브 프로젝트",               subtitle: "인간의 시인 위계를 중심으로 다변화된 성과 설계와 개선 목적의 상세한 실무 분석 자료입니다." },
    process:  { badge: "03 | WORKFLOW",               title: "문제를 해결하는 6단계 프로덕션 궤도",        subtitle: "브랜드 전략 수립부터 매체별 퍼블리싱까지 가치가 고르게 순환하도록 이끕니다." },
    portfolio: { badge: "04 | GALLERY",               title: "제작 이미지 포트폴리오",                     subtitle: "SNS 및 마케팅 캠페인 기획 운영 시 직접 기획하고 제작했던 핵심 크리에이티브 시안들입니다." },
    skills:   { badge: "05 | SKILLS MATRIX",          title: "분야별 실무 도구 숙련도",                   subtitle: "아이디어 시연 속도를 보장하고 소통 비용을 아껴드리는 핵심 수치입니다." },
    career:   { badge: "06 | CAREER // 경력",          title: "경력",                                     subtitle: "내실 있고 옹골차게 키워 온 귀중한 타임라인 이력입니다." },
    contact:  { badge: "07 | CONTACT",                title: "귀사와 함께 반응하고 성과 내는 콘텐츠를 설계하겠습니다.", subtitle: "면접 전형 제안 및 피드백은 아래 연락처로 언제든 안내 주시기 바랍니다." }
  }
};
